# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('tercero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'verbose_name': 'Categoría',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('idMovimientoInventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idUsuarioCreacion', models.IntegerField()),
                ('pedidoCompra', models.ForeignKey(blank=True, db_column='idPedidoCompra', null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.PedidoCompra')),
            ],
            options={
                'db_table': 'MovimientoInventario',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventarioPosicion',
            fields=[
                ('idMovimientoInventarioPosicion', models.BigAutoField(primary_key=True, serialize=False)),
                ('entradaSalida', models.BooleanField()),
                ('cantidadMovimiento', models.IntegerField()),
                ('valorMovimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('movimientoInventario', models.ForeignKey(db_column='idMovimientoInventario', on_delete=django.db.models.deletion.PROTECT, to='inventario.MovimientoInventario')),
            ],
            options={
                'db_table': 'MovimientoInventarioPosicion',
            },
        ),
        migrations.CreateModel(
            name='PorcentajeGanancia',
            fields=[
                ('idPorcentajeGanancia', models.BigAutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=4)),
                ('categoria', models.ForeignKey(blank=True, db_column='idCategoria', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.Categoria')),
            ],
            options={
                'db_table': 'PorcentajeGanancia',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.BigAutoField(primary_key=True, serialize=False)),
                ('numeroProducto', models.BigIntegerField(unique=True, verbose_name='Número Producto')),
                ('nombre', models.CharField(max_length=150)),
                ('referencia', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=1000)),
                ('especificacion', models.TextField(blank=True, max_length=1000, null=True)),
                ('urldescripcion', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('categoria', models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.PROTECT, to='inventario.Categoria')),
                ('marca', models.ForeignKey(db_column='idMarca', on_delete=django.db.models.deletion.PROTECT, to='inventario.Marca')),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('idProductoImagen', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=0)),
                ('imagen', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
            ],
            options={
                'db_table': 'ProductoImagen',
                'verbose_name': 'Producto Imagen',
                'verbose_name_plural': 'Producto Imagenes',
            },
        ),
        migrations.CreateModel(
            name='ProductoReview',
            fields=[
                ('idProductoReview', models.BigAutoField(primary_key=True, serialize=False)),
                ('numeroVista', models.BigIntegerField()),
                ('numeroVenta', models.BigIntegerField()),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, to='inventario.Producto')),
            ],
            options={
                'db_table': 'ProductoReview',
            },
        ),
        migrations.CreateModel(
            name='SaldoInventario',
            fields=[
                ('idSaldoInventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costoTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Total')),
                ('precioVentaUnitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio venta Unitario')),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, to='inventario.Producto')),
                ('proveedor', models.ForeignKey(db_column='idProveedor', on_delete=django.db.models.deletion.PROTECT, to='tercero.Proveedor')),
                ('usuarioCreacion', models.ForeignKey(db_column='idUsuarioCreacion', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SaldoInventario',
                'verbose_name': 'Saldo Inventario',
                'verbose_name_plural': 'Saldo Inventario',
            },
        ),
        migrations.AddField(
            model_name='porcentajeganancia',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='idProducto', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.Producto'),
        ),
        migrations.AddField(
            model_name='movimientoinventarioposicion',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, to='inventario.Producto'),
        ),
        migrations.AddField(
            model_name='movimientoinventarioposicion',
            name='proveedor',
            field=models.ForeignKey(db_column='idProveedor', on_delete=django.db.models.deletion.PROTECT, to='tercero.Proveedor'),
        ),
    ]
