# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='pedidoVenta',
            field=models.ForeignKey(blank=True, db_column='idPedidoVenta', null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.PedidoVenta'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoriaPadre',
            field=models.ForeignKey(blank=True, db_column='idCategoriaPadre', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Categoria', verbose_name='Categoría Padre'),
        ),
        migrations.AlterUniqueTogether(
            name='saldoinventario',
            unique_together=set([('producto', 'proveedor')]),
        ),
        migrations.AlterUniqueTogether(
            name='productoimagen',
            unique_together=set([('producto', 'order')]),
        ),
    ]
