# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20170313_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
