# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('inventario', '0004_auto_20170316_1558'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoimagen',
            unique_together=set([('producto', 'imagen', 'order')]),
        ),
    ]
