# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20170317_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='especificacion',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
