# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20170321_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldoinventario',
            name='referenciaProveedor',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
