# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_saldoinventario_referenciaproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idPromocion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=18)),
                ('precioVentaPromocion', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fechaInicio', models.DateTimeField(blank=True, null=True)),
                ('fechaFin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'Promocion',
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.AlterField(
            model_name='saldoinventario',
            name='referenciaProveedor',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Referencia Proveedor'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='saldoInventario',
            field=models.ForeignKey(db_column='idSaldoInventario', on_delete=django.db.models.deletion.PROTECT, to='inventario.SaldoInventario'),
        ),
    ]
