# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20170329_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='fechaFin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fechaInicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='idPromocion',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='precioVentaPromocion',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio Promocion'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='saldoInventario',
            field=models.ForeignKey(db_column='idSaldoInventario', on_delete=django.db.models.deletion.PROTECT, to='inventario.SaldoInventario', verbose_name='Saldo Inventario'),
        ),
    ]
