# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20170329_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='precioVentaPromocion',
            new_name='precioOferta',
        ),
        migrations.AddField(
            model_name='saldoinventario',
            name='precioOferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Oferta'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fechaInicio',
            field=models.DateTimeField(auto_now_add=True, default='2017-03-27', verbose_name='Fecha Inicio'),
            preserve_default=False,
        ),
    ]
