# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_auto_20170329_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldoinventario',
            name='precioCompraUnitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Compra Unitario'),
        ),
    ]
