# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_saldoinventario_preciocompraunitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='precioOferta',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio Oferta'),
        ),
    ]
