# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auto_20170415_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('idGarantia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(max_length=2, unique=True)),
                ('descripcion', models.TextField(max_length=150)),
            ],
            options={
                'db_table': 'Garantia',
            },
        ),
        migrations.AddField(
            model_name='saldoinventario',
            name='garantia',
            field=models.ForeignKey(blank=True, db_column='idGarantia', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.Garantia'),
        ),
    ]
