# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_auto_20170417_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='codigo',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
    ]
