# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_categoria_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
