# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_auto_20170516_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('idPlataforma', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='saldoinventario',
            name='plataformas',
            field=models.ManyToManyField(to='inventario.Plataforma'),
        ),
    ]
