# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_auto_20170716_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldoinventario',
            name='plataformas',
            field=models.ManyToManyField(blank=True, null=True, to='inventario.Plataforma'),
        ),
    ]
