# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_auto_20170716_1152'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plataforma',
            table='Plataforma',
        ),
    ]
