# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_auto_20170718_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldoinventario',
            name='plataformas',
        ),
        migrations.AddField(
            model_name='producto',
            name='plataformas',
            field=models.ManyToManyField(blank=True, to='inventario.Plataforma'),
        ),
    ]
