# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('compras', '0002_auto_20170313_1256'),
        ('filer', '0007_auto_20161016_1055'),
        ('tercero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedidoVenta',
            fields=[
                ('idEstadoPedidoVenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Estado Pedido Venta',
                'verbose_name': 'Estado Pedido Venta',
                'db_table': 'EstadoPedidoVenta',
            },
        ),
        migrations.CreateModel(
            name='ParametroImpuesto',
            fields=[
                ('idParametroImpuesto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=20)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'ParametroImpuesto',
            },
        ),
        migrations.CreateModel(
            name='PedidoVenta',
            fields=[
                ('idPedidoVenta', models.BigAutoField(primary_key=True, serialize=False)),
                ('numeroPedido', models.BigIntegerField(unique=True, verbose_name='Número Pedido')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fechaAutorizacion', models.DateTimeField(blank=True, db_column='fechaAutorizacion', null=True)),
                ('idUsuarioCreacion', models.IntegerField()),
                ('cliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.PROTECT, to='tercero.Cliente')),
                ('estadoPedidoVenta', models.ForeignKey(db_column='idEstadoPedidoVenta', on_delete=django.db.models.deletion.PROTECT, to='ventas.EstadoPedidoVenta')),
                ('urlFactura', filer.fields.file.FilerFileField(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='Url Factura')),
            ],
            options={
                'permissions': (('autorizar_pedido', 'Puede autorizar pedidos de venta'), ('consultar_pedido', 'Puede consultar los pedidos de venta')),
                'db_table': 'PedidoVenta',
            },
        ),
        migrations.CreateModel(
            name='PedidoVentaPosicion',
            fields=[
                ('idPedidoVentaPosicion', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costoTotal', models.DecimalField(db_column='costoTotal', decimal_places=2, max_digits=10)),
                ('pedidoVenta', models.ForeignKey(db_column='idPedidoVenta', on_delete=django.db.models.deletion.PROTECT, to='ventas.PedidoVenta')),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, to='inventario.Producto')),
                ('proveedor', models.ForeignKey(db_column='idProveedor', on_delete=django.db.models.deletion.PROTECT, to='tercero.Proveedor')),
            ],
            options={
                'db_table': 'PedidoVentaPosicion',
            },
        ),
        migrations.CreateModel(
            name='PosicionVentaCompra',
            fields=[
                ('idPosicionVentacompra', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('pedidoCompraPosicion', models.ForeignKey(db_column='idPedidoCompraPosicion', on_delete=django.db.models.deletion.PROTECT, to='compras.PedidoCompraPosicion')),
                ('pedidoVentaPosicion', models.ForeignKey(db_column='idPedidoVentaPosicion', on_delete=django.db.models.deletion.PROTECT, to='ventas.PedidoVentaPosicion')),
            ],
            options={
                'db_table': 'PosicionVentaCompra',
            },
        ),
        migrations.CreateModel(
            name='RangoNumeroPedidoVenta',
            fields=[
                ('idRangoNumeroPedidoVenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=15)),
                ('numeroDesde', models.BigIntegerField(verbose_name='Número Desde')),
                ('numeroHasta', models.BigIntegerField(verbose_name='Número Hasta')),
                ('numeroActual', models.BigIntegerField(verbose_name='Número Actual')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Rango Número Pedido',
                'verbose_name': 'Rango Número Pedido',
                'db_table': 'RangoNumeroPedidoVenta',
            },
        ),
    ]
