# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoventa',
            options={'permissions': (('autorizar_pedido', 'Puede autorizar pedidos de venta'), ('consultar_pedido', 'Puede consultar los pedidos de venta'), ('reportes', 'Puede generar reportes'))},
        ),
    ]
