# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20170424_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoCancelacionPedidoVenta',
            fields=[
                ('idMotivoCancelacionPedidoVenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'MotivoCancelacionPedidoVenta',
            },
        ),
        migrations.AlterModelOptions(
            name='pedidoventa',
            options={'permissions': (('autorizar_pedido', 'Puede autorizar pedidos de venta'), ('consultar_pedido', 'Puede consultar los pedidos de venta'), ('modificar_pedido', 'Puede modificar los pedidos'), ('reportes', 'Puede generar reportes'))},
        ),
        migrations.AddField(
            model_name='pedidoventaposicion',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoventa',
            name='motivoCancelacionPedidoVenta',
            field=models.ForeignKey(blank=True, db_column='idMotivoCancelacionPedidoVenta', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.MotivoCancelacionPedidoVenta'),
        ),
        migrations.AddField(
            model_name='pedidoventaposicion',
            name='motivoCancelacionPedidoVenta',
            field=models.ForeignKey(blank=True, db_column='idMotivoCancelacionPedidoVenta', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.MotivoCancelacionPedidoVenta'),
        ),
    ]
