# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20170424_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoventaposicion',
            options={'permissions': (('cancelar_pedido_venta_posicion', 'Puede cancelar pedidos de venta'),)},
        ),
    ]
