# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20170424_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoventa',
            options={'permissions': (('autorizar_pedido', 'Puede autorizar pedidos de venta'), ('consultar_pedido', 'Puede consultar los pedidos de venta'), ('reportes', 'Puede generar reportes'))},
        ),
        migrations.AlterField(
            model_name='pedidoventa',
            name='motivoCancelacionPedidoVenta',
            field=models.ForeignKey(blank=True, db_column='idMotivoCancelacionPedidoVenta', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.MotivoCancelacionPedidoVenta', verbose_name='Motivo Cancelación'),
        ),
        migrations.AlterField(
            model_name='pedidoventaposicion',
            name='motivoCancelacionPedidoVenta',
            field=models.ForeignKey(blank=True, db_column='idMotivoCancelacionPedidoVenta', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.MotivoCancelacionPedidoVenta', verbose_name='Motivo Cancelación'),
        ),
    ]
