# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepartamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idMunicipio', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=30)),
                ('departamento', models.ForeignKey(db_column='idDepartamento', on_delete=django.db.models.deletion.PROTECT, to='division_territorial.Departamento')),
            ],
            options={
                'db_table': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'db_table': 'Pais',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(db_column='idPais', on_delete=django.db.models.deletion.PROTECT, to='division_territorial.Pais'),
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together=set([('departamento', 'codigo')]),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set([('pais', 'codigo')]),
        ),
    ]
