# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('division_territorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('idBanco', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Banco',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=150)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='DatoBasicoTercero',
            fields=[
                ('idDatoBasicoTercero', models.BigAutoField(primary_key=True, serialize=False)),
                ('nit', models.BigIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('primerNombre', models.CharField(blank=True, max_length=15, null=True, verbose_name='Primer Nombre')),
                ('segundoNombre', models.CharField(blank=True, max_length=15, null=True, verbose_name='Segundo Nombre')),
                ('primerApellido', models.CharField(blank=True, max_length=15, null=True, verbose_name='Primer Apellido')),
                ('segundoApellido', models.CharField(blank=True, max_length=15, null=True, verbose_name='Segundo Apellido')),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Terceros',
                'verbose_name': 'Tercero',
                'db_table': 'DatoBasicoTercero',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('idMetodoPago', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Métodos de Pago',
                'verbose_name': 'Método Pago',
                'db_table': 'MetodoPago',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=150)),
                ('webSite', models.CharField(max_length=150, verbose_name='Web Site')),
                ('datoBasicoTercero', models.ForeignKey(db_column='idDatoBasicoTercero', on_delete=django.db.models.deletion.PROTECT, to='tercero.DatoBasicoTercero', verbose_name='Tercero')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='ProveedorCuenta',
            fields=[
                ('idProveedorCuenta', models.BigAutoField(primary_key=True, serialize=False)),
                ('numeroCuenta', models.CharField(max_length=100, verbose_name='Número Cuenta')),
                ('banco', models.ForeignKey(db_column='idBanco', on_delete=django.db.models.deletion.PROTECT, to='tercero.Banco')),
                ('metodoPago', models.ForeignKey(db_column='idMetodoPago', on_delete=django.db.models.deletion.PROTECT, to='tercero.MetodoPago', verbose_name='Método Pago')),
                ('proveedor', models.ForeignKey(db_column='idProveedor', on_delete=django.db.models.deletion.PROTECT, to='tercero.Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Proveedor Cuenta',
                'verbose_name': 'Proveedor Cuenta',
                'db_table': 'ProveedorCuenta',
            },
        ),
        migrations.CreateModel(
            name='ProveedorOficina',
            fields=[
                ('idProveedorOficina', models.BigAutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('municipio', models.ForeignKey(db_column='idMunicipio', on_delete=django.db.models.deletion.PROTECT, to='division_territorial.Municipio')),
                ('proveedor', models.ForeignKey(db_column='idProveedor', on_delete=django.db.models.deletion.PROTECT, to='tercero.Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Proveedor Oficinas',
                'db_table': 'ProveedorOficina',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('idTipoCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Tipo Cuenta',
                'verbose_name': 'Tipo Cuenta',
                'db_table': 'TipoCuenta',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('idTipoDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipo Documento',
                'verbose_name': 'Tipo Documento',
                'db_table': 'TipoDocumento',
            },
        ),
        migrations.AddField(
            model_name='proveedorcuenta',
            name='tipoCuenta',
            field=models.ForeignKey(db_column='idTipoCuenta', on_delete=django.db.models.deletion.PROTECT, to='tercero.TipoCuenta', verbose_name='Tipo Cuenta'),
        ),
        migrations.AddField(
            model_name='datobasicotercero',
            name='tipoDocumento',
            field=models.ForeignKey(db_column='idTipoDocumento', on_delete=django.db.models.deletion.PROTECT, to='tercero.TipoDocumento', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='datoBasicoTercero',
            field=models.OneToOneField(db_column='idDatoBasicoTercero', on_delete=django.db.models.deletion.PROTECT, to='tercero.DatoBasicoTercero', verbose_name='Tercero'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.ForeignKey(db_column='idMunicipio', on_delete=django.db.models.deletion.PROTECT, to='division_territorial.Municipio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(db_column='idUsuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
