# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedoroficina',
            options={'verbose_name': 'Proveedor Oficina', 'verbose_name_plural': 'Proveedor Oficinas'},
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='datoBasicoTercero',
            field=models.OneToOneField(db_column='idDatoBasicoTercero', on_delete=django.db.models.deletion.PROTECT, to='tercero.DatoBasicoTercero', verbose_name='Tercero'),
        ),
    ]
