# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('idCarousel', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('imagen', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
        ),
    ]
