# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_carousel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSincronizacion',
            fields=[
                ('idApiSincronizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Sincronización')),
            ],
            options={
                'verbose_name': 'API Sincronización',
                'verbose_name_plural': 'API Sincronización',
                'db_table': 'ApiSincronizacion',
            },
        ),
        migrations.CreateModel(
            name='ApiTabla',
            fields=[
                ('idApiTabla', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'API Tabla',
                'verbose_name_plural': 'API Tablas',
                'db_table': 'ApiTabla',
            },
        ),
        migrations.AddField(
            model_name='apisincronizacion',
            name='tabla',
            field=models.ForeignKey(db_column='idApiTabla', on_delete=django.db.models.deletion.CASCADE, to='base.ApiTabla', verbose_name='API Tabla'),
        ),
    ]
