# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170603_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisincronizacion',
            name='ultima',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apisincronizacion',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha Sincronización'),
        ),
    ]
