# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170604_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisincronizacion',
            name='tabla',
            field=models.ForeignKey(blank=True, db_column='idApiTabla', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ApiTabla', verbose_name='API Tabla'),
        ),
        migrations.AlterField(
            model_name='apisincronizacion',
            name='ultima',
            field=models.BooleanField(default=True),
        ),
    ]
