# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_auto_20170516_2348'),
        ('filer', '0007_auto_20161016_1055'),
        ('base', '0005_auto_20170604_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBanner',
            fields=[
                ('idApiBanner', models.AutoField(primary_key=True, serialize=False)),
                ('isClickable', models.BooleanField(default=False)),
                ('urlResultado', models.CharField(blank=True, max_length=256, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('imagen', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
                ('saldoInventario', models.ForeignKey(blank=True, db_column='idSaldoInventario', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.SaldoInventario', verbose_name='Saldo Inventario')),
            ],
            options={
                'verbose_name': 'Api Banner',
                'verbose_name_plural': 'Api Banner',
                'db_table': 'ApiBanner',
            },
        ),
    ]
