# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_apibanner_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apibanner',
            old_name='urlResultado',
            new_name='urlRequest',
        ),
    ]
