# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20170630_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSection',
            fields=[
                ('idApiSection', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('subTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('urlRequestProductos', models.CharField(max_length=256)),
                ('urlRequestMas', models.CharField(blank=True, max_length=256, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Api Section',
                'verbose_name_plural': 'Api Sections',
                'db_table': 'ApiSection',
            },
        ),
        migrations.AlterField(
            model_name='apisincronizacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Sincronización'),
        ),
    ]
