# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 15:10
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0002_auto_20170321_2359'),
        ('base', '0011_auto_20170708_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoModificacionPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/bikerlfh/uploads/'), upload_to='xls/', verbose_name='Archivo')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ultimo', models.BooleanField(default=True)),
                ('proveedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tercero.Proveedor')),
            ],
            options={
                'verbose_name': 'Archivo modificacion precios',
                'verbose_name_plural': 'Archivos modificación precios',
                'db_table': 'ArchivoModificacionPrecio',
            },
        ),
    ]
