# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 13:26
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_archivomodificacionprecio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivomodificacionprecio',
            options={'verbose_name': 'Archivo modificación precios', 'verbose_name_plural': 'Archivos modificación precios'},
        ),
        migrations.AlterField(
            model_name='archivomodificacionprecio',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/var/tmp/shopneubs/uploads/'), upload_to='precios/', verbose_name='Archivo'),
        ),
    ]
