# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedidoCompra',
            fields=[
                ('idEstadoPedidoCompra', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Estado Pedido Compra',
                'verbose_name': 'Estado Pedido Compra',
                'db_table': 'EstadoPedidoCompra',
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('idPedidoCompra', models.BigAutoField(primary_key=True, serialize=False)),
                ('numeroPedido', models.BigIntegerField(db_column='numeroPedido', unique=True, verbose_name='Número Pedido')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idUsuarioCreacion', models.BigIntegerField()),
            ],
            options={
                'permissions': (('solicitar_compra', 'Puede solicitar pedido de compra'), ('consultar_pedido', 'Puede consultar el pedido de compra')),
                'db_table': 'PedidoCompra',
            },
        ),
        migrations.CreateModel(
            name='PedidoCompraPosicion',
            fields=[
                ('idPedidoCompraPosicion', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costoTotal', models.DecimalField(db_column='costoTotal', decimal_places=2, max_digits=10)),
                ('pedidoCompra', models.ForeignKey(db_column='idPedidoCompra', on_delete=django.db.models.deletion.PROTECT, to='compras.PedidoCompra')),
            ],
            options={
                'db_table': 'PedidoCompraPosicion',
            },
        ),
        migrations.CreateModel(
            name='RangoNumeroPedidoCompra',
            fields=[
                ('idRangoNumeroPedidoCompra', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=15)),
                ('numeroDesde', models.BigIntegerField(verbose_name='Número Desde')),
                ('numeroHasta', models.BigIntegerField(verbose_name='Número Hasta')),
                ('numeroActual', models.BigIntegerField(verbose_name='Número Actual')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Rango Número Pedido',
                'verbose_name': 'Rango Número Pedido',
                'db_table': 'RangoNumeroPedidoCompra',
            },
        ),
    ]
