# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('filer', '0007_auto_20161016_1055'),
        ('tercero', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocompraposicion',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, to='inventario.Producto'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='estadoPedidoCompra',
            field=models.ForeignKey(db_column='idEstadoPedidoCompra', on_delete=django.db.models.deletion.PROTECT, to='compras.EstadoPedidoCompra', verbose_name='Estado Pedido'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='proveedor',
            field=models.ForeignKey(db_column='idProveedor', on_delete=django.db.models.deletion.PROTECT, to='tercero.Proveedor'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='urlFactura',
            field=filer.fields.file.FilerFileField(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='Url Factura'),
        ),
    ]
